// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDE-jxN--4hgc4M7fowI-EHecuSHk-nn2I',
    appId: '1:475666154233:web:61ba47e3b771384ab09828',
    messagingSenderId: '475666154233',
    projectId: 'projectbisamasak',
    authDomain: 'projectbisamasak.firebaseapp.com',
    storageBucket: 'projectbisamasak.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBleDUgqz4NfhMPMJJnwjEakI2E9mcQbr4',
    appId: '1:475666154233:android:d57530af069e19bbb09828',
    messagingSenderId: '475666154233',
    projectId: 'projectbisamasak',
    storageBucket: 'projectbisamasak.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3Lkjb2gdnZ3ksJ6QlPbxeHHrabUdReA4',
    appId: '1:475666154233:ios:49dcb4ce9161374cb09828',
    messagingSenderId: '475666154233',
    projectId: 'projectbisamasak',
    storageBucket: 'projectbisamasak.appspot.com',
    iosBundleId: 'com.example.bisa',
  );
}
